<?php

namespace HangmanBundle\Repository;

/**
 * sessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sessionRepository extends \Doctrine\ORM\EntityRepository
{
}
