<?php

namespace HangmanBundle\Repository;

/**
 * wordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wordRepository extends \Doctrine\ORM\EntityRepository
{
}
